var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#ff3333",
    warna_grup_hijau: "#ffcc00",
    warna_grup_kuning: "#ff6600",
    warna_garis_tebal: "#ff4444",
    warna_garis_biasa: "#882222",
    warna_jarum_speedo: "#ff0000",
    warna_jarum_tacho: "#ff5500",
    warna_redline: "#ff0000",
    warna_background_utama: "#140a0a",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "0.85",
    kecerahan_gambar: "0.6",
    ukuran_font_mobil: "20",
};
