var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#ff33cc",
    warna_grup_hijau: "#00ffff",
    warna_grup_kuning: "#ffaa00",
    warna_garis_tebal: "#9933ff",
    warna_garis_biasa: "#221144",
    warna_jarum_speedo: "#00e5ff",
    warna_jarum_tacho: "#ff5500",
    warna_redline: "#ff0055",
    warna_background_utama: "#070714",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "0.9",
    kecerahan_gambar: "0.8",
    ukuran_font_mobil: "17",
};
