var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#ffffff",
    warna_grup_hijau: "#e6e6fa",
    warna_grup_kuning: "#ffcc00",
    warna_garis_tebal: "#8a2be2",
    warna_garis_biasa: "#1a0033",
    warna_jarum_speedo: "#b366ff",
    warna_jarum_tacho: "#ff3333",
    warna_redline: "#ff0033",
    warna_background_utama: "#05020a",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "0.9",
    kecerahan_gambar: "0.65",
    ukuran_font_mobil: "17",
};
