var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#ffffff",
    warna_grup_hijau: "#00e5ff",
    warna_grup_kuning: "#99ccff",
    warna_garis_tebal: "#00aaff",
    warna_garis_biasa: "#003366",
    warna_jarum_speedo: "#00ffff",
    warna_jarum_tacho: "#00ccff",
    warna_redline: "#ff3366",
    warna_background_utama: "#020813",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "0.85",
    kecerahan_gambar: "0.75",
    ukuran_font_mobil: "18",
};
