var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#04ff00",
    warna_grup_hijau: "#04ff00",
    warna_grup_kuning: "#04ff00",
    warna_garis_tebal: "#04ff00",
    warna_garis_biasa: "#04ff00",
    warna_jarum_speedo: "#ff0000",
    warna_jarum_tacho: "#ffb347",
    warna_redline: "#ff3b30",
    warna_background_utama: "#0b0d10",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "false",
    opasitas_gambar: "1",
    kecerahan_gambar: "1",
    ukuran_font_mobil: "16",
};
