var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#00eeff",
    warna_grup_hijau: "#eef2f6",
    warna_grup_kuning: "#eef2f6",
    warna_garis_tebal: "#00ccff",
    warna_garis_biasa: "#0008ff",
    warna_jarum_speedo: "#ff0000",
    warna_jarum_tacho: "#ffb347",
    warna_redline: "#ff3b30",
    warna_background_utama: "#0b0d10",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "1",
    kecerahan_gambar: "0.6",
    ukuran_font_mobil: "16",
};
