var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#ffffff",
    warna_grup_hijau: "#ffe6ea",
    warna_grup_kuning: "#c796e8",
    warna_garis_tebal: "#cc0022",
    warna_garis_biasa: "#4a000a",
    warna_jarum_speedo: "#ff0033",
    warna_jarum_tacho: "#0073e6",
    warna_redline: "#ff3366",
    warna_background_utama: "#080002",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "0.9",
    kecerahan_gambar: "0.55",
    ukuran_font_mobil: "18",
};
