var THEME_CONFIG = {
    font_utama: "'Rajdhani', sans-serif",
    font_angka: "'Oxanium', monospace",
    font_angka_speedo: "'Rajdhani', sans-serif",
    warna_grup_merah: "#ffffff",
    warna_grup_hijau: "#e6f0ff",
    warna_grup_kuning: "#d98c94",
    warna_garis_tebal: "#3a7df0",
    warna_garis_biasa: "#21396b",
    warna_jarum_speedo: "#3a7df0",
    warna_jarum_tacho: "#d98c94",
    warna_redline: "#ff4d6d",
    warna_background_utama: "#080a12",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "true",
    opasitas_gambar: "0.9",
    kecerahan_gambar: "0.55",
    ukuran_font_mobil: "17",
};
