var THEME_CONFIG = {
    font_utama: "'Audiowide', cursive",
    font_angka: "'Orbitron', sans-serif",
    font_angka_speedo: "'Orbitron', sans-serif",
    warna_grup_merah: "#ffffff",
    warna_grup_hijau: "#ffffff",
    warna_grup_kuning: "#ffffff",
    warna_garis_tebal: "#00fbff",
    warna_garis_biasa: "#00fbff",
    warna_jarum_speedo: "#ff0000",
    warna_jarum_tacho: "#ffb347",
    warna_redline: "#ff3b30",
    warna_background_utama: "#0b0d10",
    jarak_meteran: "0",
    tampilkan_kotak_digital: "false",
    opasitas_gambar: "1",
    kecerahan_gambar: "0.6",
    ukuran_font_mobil: "16",
};
